language: ruby
rvm:
  - 2.0.0
services:
  - postgresql
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - PORT=3002 bundle exec foreman start &
  - sleep 3
script:
  - bundle exec rake test
  - bundle exec rake karma:ci
