development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: festive_development
  pool: 5
  pool_timeout: 360
  connect_timeout: 360

test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: festive_test
  username: postgres
  pool: 5
  pool_timeout: 360
  connect_timeout: 360

production:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: festive_production
  pool: 5
  pool_timeout: 360
  connect_timeout: 360
